name: Test Formula

on:
  pull_request:
    paths:
      - 'Formula/**'
      - '.github/workflows/test-formula.yml'
  workflow_dispatch:
  push:
    branches: [ master, main ]
    paths:
      - 'Formula/**'

jobs:
  test-formula:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate formula syntax
        run: brew style Formula/gedkeeper3.rb

      - name: Add tap for testing
        run: brew tap --force homebrew/test ${{ github.workspace }}

      - name: Audit formula
        run: brew audit --formula homebrew/test/gedkeeper3

      - name: Install formula
        run: brew install --formula --verbose homebrew/test/gedkeeper3

      - name: Verify installation
        run: |
          set -e
          if [ ! -d "$(brew --prefix)/opt/gedkeeper3/GEDKeeper3.app" ]; then
            echo "GEDKeeper3.app not found in formula prefix"
            exit 1
          fi
          
          echo "GEDKeeper3.app successfully installed to formula prefix"
          ls -la "$(brew --prefix)/opt/gedkeeper3/"
          
          if [ ! -L "/Applications/GEDKeeper3.app" ]; then
            echo "Symlink to /Applications/GEDKeeper3.app not found"
            exit 1
          fi
          
          echo "Symlink to Applications folder created successfully"
          ls -la "/Applications/GEDKeeper3.app"

      - name: Run formula test
        run: brew test --formula homebrew/test/gedkeeper3

      - name: Test uninstallation
        run: |
          set -e
          brew uninstall --formula homebrew/test/gedkeeper3
          
          if [ -d "$(brew --prefix)/opt/gedkeeper3" ]; then
            echo "Formula files still exist after uninstall"
            exit 1
          fi
          
          if [ -L "/Applications/GEDKeeper3.app" ]; then
            echo "Symlink still exists after uninstall"
            exit 1
          fi
          
          echo "Formula successfully uninstalled"

      - name: Clean up
        if: always()
        run: |
          brew untap homebrew/test || true
          rm -rf "/Applications/GEDKeeper.app" 2>/dev/null || true